name: tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main
  
jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Run tests
        run: dotnet test
